### ISSUE TITLE
Odd quirk with Easier Enchanting

### ISSUE THREAD

**Issue by saransh323** [SmushyTaco/Expanded-Armor-Enchanting#1]
The mod EasierEnchanting is used to show all the enchants that will be received on enchanting an item via themenchanting table. 

However, when installed with Expander Armor Enchanting, the enchanting tooltip shows a list of enchantments, but one of the (otherwise) hidden enchants is replaced with a protection enchant in case of armor.

Is it possible to have the extra protection enchant as a separate/additional one and/or have support for easier enchanting?

What it shows, and the enchants it should get:
![image](https://user-images.githubusercontent.com/24824351/127542671-f2034d94-df0f-4658-a7b6-f427c24a3dab.png)

What happens:
![image](https://user-images.githubusercontent.com/24824351/127542881-cdea8094-3611-45f0-b09e-6d0ed7f3545e.png)

**Comment by SmushyTaco** [comment]
I'm not seeing anything in my code that could be causing this issue since it's a pretty simple mod, you should open an issue on the Easier Enchanting mod's GitHub it sounds like that's an issue with their mod.

**Comment by saransh323** [comment]
Oh, ok. I'll do that.
