### ISSUE TITLE
wrong dependencies

### ISSUE THREAD

**Issue by calloatti** [SmushyTaco/Expanded-Armor-Enchanting#3]
expanded-armor-enchanting-1.0.3.jar
expanded-weapon-enchanting-1.0.3.jar

Both have errors in fabric.mod.json

the "-" in the  mod ids for the dependencies has been replaced with "_"

**Comment by SmushyTaco** [comment]
I just tested the mods and it handles dependencies fine, I used the latest loader version, latest minecraft version, the latest cloth config version, the latest fabric api version, and the latest fabric language kotlin version. I'm confused on what the issue is exactly.

**Comment by calloatti** [comment]
Yes, I have no idea what was going on yesterday, cannot reproduce now. Basically I was seeing this:

 ```
 "depends": {
    "fabricloader": ">=0.14.9",
    "fabric-api": "*",
    "fabric_language_kotlin": ">=1.8.2+kotlin.1.7.10",
    "minecraft": "~1.19",
    "cloth_config2": ">=8.0.75",
    "java": ">=17"
```

**Comment by calloatti** [comment]
The problem is my `fabric_loader_dependencies.json` generator was broken. Sorry
